### ISSUE TITLE
Downloading website files

### ISSUE THREAD

**Issue by DeputyofDisorder** [rapodaca/team-site#1]
Hey Rich,

I can't remember the commands that you told us when in Powershell to manipulate node and github to open the files in github on our atom.

**Comment by rapodaca** [comment]
To clone (download) the repository to your local machine:

```bash
git clone {url}
```

Where `{url}` is the GitHub https URL to the repository.

Then change into the cloned repository:

```bash
cd team-site
```

To open the project in Atom:

```bash
atom .
```

To install dependencies:

```bash
npm install
```

To start the server:

```
npm start
```

If any of these fail, you can post the output from PowerShell as part of your response.
